//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoteFinal
    {
        public int Vid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Email { get; set; }
        public bool VBitcoin { get; set; }
        public bool VEthereum { get; set; }
        public bool VBitcoinCash { get; set; }
        public bool VLitecoin { get; set; }
        public bool VRipple { get; set; }
    }
}
